POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "per"
}

###

GET http://localhost:3000/events/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGVyIiwiaWF0IjoxNjAxMzcyMjg2LCJleHAiOjE2MDEzNzIzNDZ9.duBZ8z5b0T6pfTfuD4S9g1mTkgbsMmzf1sBWL6D9Z8c

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDEzNzIyMjQsImV4cCI6MTYwMTM3MjI4NH0.WzRwehwMjGvJgof5W8H4oHSh3cBvDRQa-FTs38WSRHU"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDEzNzIyMjQsImV4cCI6MTYwMTM3MjI4NH0.WzRwehwMjGvJgof5W8H4oHSh3cBvDRQa-FTs38WSRHU"
}