POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

###

GET http://localhost:3000/events/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE4MzY1OTgsImV4cCI6MTYwMTgzNjY1OH0.Znv1rQaf4o5OLutIGY-1OWgenToCnZhRIi8gO4emGF0

{
    "date": "torsdag",
    "isBooked": false,
    "creator": "per"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDEzNzIyMjQsImV4cCI6MTYwMTM3MjI4NH0.WzRwehwMjGvJgof5W8H4oHSh3cBvDRQa-FTs38WSRHU"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDEzNzIyMjQsImV4cCI6MTYwMTM3MjI4NH0.WzRwehwMjGvJgof5W8H4oHSh3cBvDRQa-FTs38WSRHU"
}